apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany # Allows multiple apps to read/write
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data" # Minikube host directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
