apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: local/api-service:v1
          env:
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
          volumeMounts:
            - mountPath: "/mnt/data"
              name: file-storage
      volumes:
        - name: file-storage
          persistentVolumeClaim:
            claimName: file-storage-claim
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: api-service
